config/routes.rb
Rails.application.routes.draw do
  resources :picks
  resources :groups
  resources :group_members
  resources :schools
  get 'sessions/new'
  resources :users
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'pages/home'
  get 'pages/live_draft'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/group.rb
class Group < ApplicationRecord
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    if current_user.present? == false
      redirect_to login_url(need_login: 'y')
    end
    @groups = Group.all
    if params['join_group'] == 'yes'
      GroupMember.create(
        group_id: params['gid'],
        user_id: params['uid'],
        ).save
      redirect_to groups_path()
      return
    end

  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :note_1, :auto_draft_complete, :live_draft_start, :auto_draft_start, :live_draft_complete, :draft_order_1, :draft_order_2, :draft_order_3, :draft_order_4)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Group Name', input_html: {class: 'form-control input_text_box'} %>
    <%#= f.input :buy_in, label: 'Add a buy in amount', input_html: {class: 'form-control input_text_box'} %>
    <%#= f.input :note_1, label: 'Add Group Note', input_html: {class: 'form-control input_text_box'} %>
    <%= f.input :auto_draft_complete, input_html: {value: false}, as: :hidden %>
    <%= f.input :live_draft_complete, input_html: {value: false}, as: :hidden %>
    <%= f.input :auto_draft_start, input_html: {value: false}, as: :hidden %>
    <%= f.input :live_draft_start, input_html: {value: false}, as: :hidden %>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Note 1:</strong>
    <%= group.note_1 %>
  </p>

  <p>
    <strong>Auto draft complete:</strong>
    <%= group.auto_draft_complete %>
  </p>

  <p>
    <strong>Live draft start:</strong>
    <%= group.live_draft_start %>
  </p>

  <p>
    <strong>Auto draft start:</strong>
    <%= group.auto_draft_start %>
  </p>

  <p>
    <strong>Live draft complete:</strong>
    <%= group.live_draft_complete %>
  </p>

  <p>
    <strong>Draft order 1:</strong>
    <%= group.draft_order_1 %>
  </p>

  <p>
    <strong>Draft order 2:</strong>
    <%= group.draft_order_2 %>
  </p>

  <p>
    <strong>Draft order 3:</strong>
    <%= group.draft_order_3 %>
  </p>

  <p>
    <strong>Draft order 4:</strong>
    <%= group.draft_order_4 %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="text-center"><%= link_to 'Create New Group', new_group_path(), class:'btn btn-outline-secondary btn-sm' %></div>
    <div class="">
    <h2>Groups</h2>
      <table class="table border">
          <thead class="table-light">
          <tr class="">
            <th class="text-muted">ID</th>
            <th class="text-center">Group</th>
            <th class="text-center">Players</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.order(:id).each do |g| %>
            <% member_1 = User.where(id: (GroupMember.where(group_id: g.id).pluck(:user_id)[0])).pluck(:email)[0] %>
            <% member_2 = User.where(id: (GroupMember.where(group_id: g.id).pluck(:user_id)[1])).pluck(:email)[0] %>
            <% member_3 = User.where(id: (GroupMember.where(group_id: g.id).pluck(:user_id)[2])).pluck(:email)[0] %>
            <% member_4 = User.where(id: (GroupMember.where(group_id: g.id).pluck(:user_id)[3])).pluck(:email)[0] %>
            <% member_count = GroupMember.where(group_id: g.id).count %>
          <tr class="">
            <td class="text-muted"><small>ID: <%= g.id %></small></td>
            <td class="text-center">
              <%= g.name %> 
              <br><br>
              <% if g.auto_draft_complete? || g.live_draft_complete? %>
                <%= link_to 'View Standings', group_path(id: g.id), class: 'btn btn-outline-success btn-sm form-control' %>
            <% elsif g.live_draft_start? %>
              <%= link_to 'Enter Live Draft', pages_live_draft_path(draft: 'live', group_id: g.id), class: 'btn btn-outline-primary btn-sm form-control' %>
            <% elsif member_count == 4 %>
               <div style="width: 100%" class="btn-group btn-group-justified" role="group">
                <%= link_to 'Auto Draft', picks_path(draft: 'auto', group_id: g.id), class: 'btn btn-outline-primary btn-sm' %>
                <% draft_order = GroupMember.where(group_id: g.id).pluck(:user_id).shuffle %>
                <%= link_to 'Live Draft', pages_live_draft_path(draft: 'live', group_id: g.id, d1: draft_order[0], d2: draft_order[1], d3: draft_order[2], d4: draft_order[3]), class: 'btn btn-outline-primary btn-sm' %>
              </div>
            <% elsif GroupMember.where(group_id: g.id).pluck(:user_id).include? current_user.id %>
                <a href="#" class="btn btn-outline-success form-control btn-sm disabled" role="button" aria-disabled="true">Waiting to fill group</a>
            <% else %>
              <%= link_to 'Join Group', groups_path(join_group: 'yes', uid: current_user.id, gid: g.id), class: 'btn btn-outline-primary btn-sm form-control' %>
            <% end %>
            </td>
            <td class="text-center">
              <%= member_1.to_s.titlecase %><br> <%= member_2.to_s.titlecase %><br> <%= member_3.to_s.titlecase %><br> <%= member_4.to_s.titlecase %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="card">
  <div class="card-body">
    <h1>New group</h1>
    <%= render "form", group: @group %>
    <br>
    <div>
      <%= link_to "Back to groups", groups_path %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="card">
  <div class="card-body">
    <% member_ids = GroupMember.where(group_id: @group.id).pluck(:user_id) %>
    <% if @group.live_draft_start? && @group.live_draft_complete? == false %>
      <div class="text-center"><%= link_to 'Go to live draft', pages_live_draft_path(draft: 'live', group_id: @group.id), class: 'btn btn-primary' %></div><br>
    <% end %>
    <h1 class="text-center"><%= @group.name %></h1>
    <p><span class="fw-bold">Details:</span> <%= @group.note_1 %></p>
    <div class="">
        <div class="row">
          <% member_ids.first(2).each do |group_member| %>
            <div class="col">
              <h5 class="text-center"><%= User.find_by(id: group_member).email.titlecase %></h5>
              <table class="table border table-hover">
                 <thead class="table-light">
                    <th>Seed</th>
                    <th>School</th>
                    <th>Region</th>
                    <th>Points</th>
                  </thead>
                <tbody>
                  <% Pick.where(group_id: @group.id, user_id: group_member).order(:created_at).all.each do |i| %>
                    <tr>
                      <td><%= School.where(id: i.school_id).pluck(:seed)[0] %></td>
                      <td><%= School.where(id: i.school_id).pluck(:name)[0] %></td>
                      <td><%= School.where(id: i.school_id).pluck(:region)[0] %></td>
                      <td></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div> 
          <% end %>
        </div>
        <div class="row">
          <% member_ids.last(2).each do |group_member| %>
            <div class="col">
              <h5 class="text-center"><%= User.find_by(id: group_member).email.titlecase %></h5>
              <table class="table border table-hover">
                 <thead class="table-light">
                    <th>Seed</th>
                    <th>School</th>
                    <th>Region</th>
                    <th>Points</th>
                  </thead>
                <tbody>
                  <% Pick.where(group_id: @group.id, user_id: group_member).all.each do |i| %>
                    <tr>
                      <td><%= School.where(id: i.school_id).pluck(:seed)[0] %></td>
                      <td><%= School.where(id: i.school_id).pluck(:name)[0] %></td>
                      <td><%= School.where(id: i.school_id).pluck(:region)[0] %></td>
                      <td></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div> 
          <% end %>
        </div>
      </div>
  </div>
</div>