config/routes.rb
Rails.application.routes.draw do
  resources :picks
  resources :groups
  resources :group_members
  resources :schools
  get 'sessions/new'
  resources :users
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'pages/home'
  get 'pages/live_draft'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/home.html.erb
<div class="card">
	<div class="card-body">
		<!-- <div class="row"> -->
			<!-- <div class="col-4"> -->
				<% if current_user.present? %>
					<div class=""><%= link_to 'View Groups', groups_path, class: 'btn btn-outline-primary form-control' %></div>
				<% else %>
					<a href="#" class="btn btn-outline-primary form-control disabled" role="button" aria-disabled="true">Signup/Login to View Groups</a>
				<% end %>
				<p class="fw-bold pt-3">My Group </p>
				<% if current_user.present? %>
				<table>
					</thead>
					<tbody>
						<% my_groups = GroupMember.where(user_id: current_user.id).pluck(:group_id) %>
						<% Group.where(id: my_groups).each do |i| %>
							<tr>
								<% if i.live_draft_start? && i.live_draft_complete? == false %>
									<td class="text-primary"><%= link_to "#{i.name} - Enter Draft", pages_live_draft_path(group_id: i.id) %></td>
								<% else %>
									<td class="text-primary"><%= link_to i.name, group_path(id: i.id) %></td>
								<% end %> 
							</tr>
						<% end %>
					</tbody>
				</table>
				<% end %>
			<!-- </div> -->
<!-- 			<div class="col-8">
				<div class="border p-3">
				<%#= image_tag("cbs-sports-2023-bracket_1.jpg", class: "img-fluid img-fluid" ) %>
				</div>
			</div> -->
		<!-- </div> -->
	</div>
</div>

app/views/pages/live_draft.html.erb
   <% group = Group.find_by(id: params['group_id']) %>
   <% group_members = GroupMember.where(group_id: group.id).pluck(:user_id) %>
   <%# member_1 = User.find_by(id: draft_order[0]) %>
   <% member_1 = User.find_by(id: group.draft_order_1) %>
   <% member_2 = User.find_by(id: group.draft_order_2) %>
   <% member_3 = User.find_by(id: group.draft_order_3) %>
   <% member_4 = User.find_by(id: group.draft_order_4) %>
   <% picks = Pick.where(group_id: group.id).pluck(:school_id) %>
   <% all_seeds = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16] %>
   <% @total_draft %>
   <% Pick.where(group_id: group.id).count %>
	<% @total_draft[Pick.where(group_id: group.id).count] %>
	<% pick_id = @total_draft[Pick.where(group_id: group.id).count] %>
	<% if Pick.where(group_id: group.id).count == 64 %>
		<% Group.where(id: group.id).update_all live_draft_complete: true %>
	<% end %>

	<% total_picks_made = Pick.where(group_id: group.id).count %>
	<% schools_picked = Pick.where(group_id: group.id).pluck(:school_id) %>
	<% next_pick = @total_draft[total_picks_made] %>


<div class="card">
	<div class="card-body">
		<h2>Live Draft</h2>
		<p><span class="fw-bold">Group:</span> <%= group.name %></p>
		<!-- <p><span class="fw-bold">Details:</span> <%= group.note_1 %></p> -->
		<!-- <p><span class="fw-bold">Snake draft order:</span><br> 1. <%= member_1.email.titlecase %><br>2. <%= member_2.email.titlecase %><br>3. <%= member_3.email.titlecase %><br>4. <%= member_4.email.titlecase %></p>	 -->
		<!-- <p><span class="fw-bold">Total picks made:</span> <%= total_picks_made %></p> -->
			<% if Pick.where(group_id: group.id).count == 64 %>
				<h3 class="text-center">Draft is over </h3>
				<span class="text-center"><%= link_to 'View teams', group_path(id: group.id), class: 'btn btn-success' %></span>
			<% else %>
				<p>
					<% if pick_id == current_user.id %> 
						<big><span class="fw-bold text-success text-center">Your Pick!</span></big>
					<% else %>
						<span class="fw-bold">Picking:</span> <span class="fw-bold text-success"><%= User.find_by(id: pick_id).email.titlecase %></span>
					<% end %>
					<% if total_picks_made < 63 %><br><span class="">Pick <%= total_picks_made + 2 %>:</span> <%= User.find_by(id: @total_draft[total_picks_made + 1]).email.titlecase %><% end %>
					<% if total_picks_made < 62 %><br><span class="">Pick <%= total_picks_made + 3 %>:</span> <%= User.find_by(id: @total_draft[total_picks_made + 2]).email.titlecase %><% end %>
					<% if total_picks_made < 61 %><br><span class="">Pick <%= total_picks_made + 4 %>:</span> <%= User.find_by(id: @total_draft[total_picks_made + 3]).email.titlecase %><% end %>
				</p>
			<% end %>
			<% unless total_picks_made == 64 %><div class="pb-3"><%= link_to 'View selections', group_path(id: group.id), class: 'btn btn-outline-primary' %></div><% end %>
				<table class="table border table-hover">
					<thead class="table-light">
						<tr>
							<th>Seed</th>
							<th>School</th>
							<th>Region</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% School.where.not(id: schools_picked).all.order(:seed).order(:region).each do |s| %>
						<tr>
							<td><%= s.seed %></td>
							<td><%= s.name %></td>
							<td><%= s.region %></td>
							<% if picks.include? s.id %>
							<td><a href="#" class="btn btn-outline-primary form-control btn-sm disabled" role="button" aria-disabled="true"><%= User.where(id: (Pick.where(group_id: group.id, school_id: s.id).pluck(:user_id)[0])).pluck(:email)[0].titlecase %></a></td>
			
							<% elsif current_user.id == pick_id %>
							<td><%= link_to  'Draft', picks_path(draft: 'live', user_id: current_user.id, group_id: group.id, school_id: s.id), class: 'btn btn-outline-success form-control btn-sm' %></td>						
							<% else %>
							<td><a href="#" class="btn btn-outline-secondary form-control btn-sm disabled" role="button" aria-disabled="true">Draft</a></td>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table> 
	</div>
</div>


<%# if current_user.id == @total_draft[total_picks_made + 1] %>
    <script>
	   setTimeout(function(){
	       location.reload();
	   },9000); // 3000 milliseconds means 3 seconds.
   </script>
 <%# end %>