config/routes.rb
Rails.application.routes.draw do
  resources :picks
  resources :groups
  resources :group_members
  resources :schools
  get 'sessions/new'
  resources :users
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'pages/home'
  get 'pages/live_draft'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarchMadnessGame1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin=“anonymous”>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
    <main>
      <header>
        <div class="container-fluid">
          <div class="row">
            <div class="col-3 pt-2">
                  <% if current_user %>
                    <p class="">
                      <%= current_user.email.titlecase %><br>
                      <%= link_to "Logout", logout_path, class: 'btn btn-outline-dark btn-sm' %>
                    </p>
                  <% else %>
                    <%#= link_to "Sign Up", signup_path, class: 'btn btn-outline-primary' %>
                    <%= link_to "Login", login_path, class: 'btn btn-outline-dark' %>
                  <% end %>
            </div>
            <div class="col-6 text-center p-2">
              <h1 class=""><%= link_to 'March Madness', pages_home_path, class: 'header-text' %></h>
            </div>
            <div class="col-3 pt-2 pb-2">

              <% unless current_user %>
                <!-- Sign Up from -->
                  <% @user = User.new %>
                  <%= simple_form_for(@user) do |f| %>
                    <%= f.error_notification %>
                    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                    <div class="form-inputs">
                      <div class="pb-2">
                        <%= f.input :email, label: false, placeholder: 'Name', input_html: {class: 'form-control input_text_box'} %>
                      </div>
                      <div class="pb-2">
                        <%= f.input :password, label: false, placeholder: 'PW', input_html: {class: 'form-control input_text_box'} %>
                      </div>
                    </div>
                    
                    <div class="form-actions">
                      <%= f.button :submit, 'Sign up', class: 'btn btn-primary btn-sm' %>
                    </div>
                  <% end %>
                <!-- END signup form -->
              <% end %>

            </div>
          </div>
        </div>
      </header>
    </main>
      <div class="container pb-5">
        <br>
    <%= yield %>
  </div>
  </body>
</html>